### ISSUE TITLE
Debugging credentials

### ISSUE THREAD

**Issue by zero-one-devteam** [fruux/sabre-dav#563]
2.1.0

I am using sabredav with Z-Push-Contrib from fmbiete (https://github.com/fmbiete/Z-Push-contrib). Problem: When receiving a meeting invitation, I don't see buttons to accept/decline the invitation. When opening the attached ics file, I see my own email address with "no answer" besides. It seems like the invitation is not properly assigned to my own calender, although the email address of the attendee matches exactly my own address. I did the setup of my principal as described here: http://sabre.io/dav/caldav-proxy/. Did I miss anything? I am having some more trobles with Mac OS X Calendar App which does not automatically recognize invitations as well, so I assume that there is any problem with my email address in sabredav. What is the best way for debugging?

**Comment by evert** [comment]
Sorry for never have gotten to a real response here. I'm closing this ticket because it's been too long and I never fully figured out what the core issue was.

If we can somehow reopen this in the future as a new ticket that has a clearer problem statement I'm definitely interested, but given the current state of this ticket I think it's best to just close it.
