### ISSUE TITLE
URL rewriting breaks due to REQUEST_URI usage

### ISSUE THREAD

**Issue by yunosh** [fruux/sabre-dav#594]
REQUEST_URI is used to detect the current path of the request. This is unreliable because URL rewriting in the web server configuration might re-route the original request (from REQUEST_URI) to a different one. Please take a look at https://github.com/horde/horde/blob/master/framework/Core/lib/Horde.php#L655 for a technique to more reliably detect the current request URL.

**Comment by Hywan** [comment]
Hello :-),

Is it a bug, an issue or a potential usecase? Please, provide an example :-).

**Comment by evert** [comment]
We've never had any issues with rewriting. From my perspective the `REQUEST_URI` always points to the url that the user would see 'in a browser'. So as @Hywan said as well, I'm interested to hear in what scenario that approach breaks down.

**Comment by yunosh** [comment]
It's some old install with different paths migrated to a sabre-based server. The existing clients should keep working without re-provisioning.
The problem is bigger than I originally assumed though. I thought changing the related methods in DAV\Server and HTTP\Request (I'm still on 1.8) would be sufficient. And it actually is, to make the old URLs work. But of course Sabre will then use those (internal, rewritten) URLs for building new URLs too. I'm not sure how happy the existing clients would be with that.

**Comment by Hywan** [comment]
@yunosh If you give us a scenario, I would be happy to dig into this issue.

**Comment by evert** [comment]
I guess what you are suggesting, is that sabre/dav is already on some working path, but then there's also a different path that gets rewritten to the initial path.

As you found out yourself, it's quite hard to make that work. One option would be for you to simply see which 'base path' is being used, and then update setBaseUrl() accordingly. This would make each endpoint at least self-consistent.

But sabre/dav needs the REQUEST_URI as well to for example be able to run in the root of a domain.

One important point though is, if you just change setBaseUrl() the implication is that for the 2 different endpoints, everything *after* the baseUrl needs to be consistent. It's not possible to have entirely different trees.

Would that work for you? Otherwise I'm simply not sure what we can do here...

**Comment by Hywan** [comment]
@yunosh: Or, you can also use redirections from the old to the new version. It could work.

**Comment by evert** [comment]
Closing this for now, let me know if there's something else can do for this @yunosh
