### ISSUE TITLE
Sabre\Client exception doesn't contain proper HTTP code

### ISSUE THREAD

**Issue by PVince81** [fruux/sabre-dav#608]
When doing a PROPFIND with Sabre\Client, sometimes it is to find out whether a resource exists. If that resource doesn't exist, we need a way to find out whether the error was 404 or something else.

However the client code now only throws a simple `\Sabre\Dav\Exception()` without any clues what the error was: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Client.php#L208

It seems that Sabre 1.8 threw specific exceptions like `\Sabre\Dav\Exception\NotFound()` for 404, so I get this was a design decision to move away from specific exceptions ?
If yes, it would be nice if that generic exception would still contain the 404 code when calling `getHTTPCode()`.

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/blob/master/lib/private/files/storage/dav.php#L167 for an example usage. If `getHTTPCode()` contains 404, I can change the catch block to react on it.

**Comment by evert** [comment]
An easy way for you to fix this locally, is to turn on '$client->throwExceptions`. Since 2.0 or so this defaults to `false`, but if you set it to `true`, then this should throw `Sabre\Http\ClientException`, which does carry the http status code as well as the _entire_ http response.

This is still a bug though.

**Comment by PVince81** [comment]
Thanks a lot, that seems to do the trick :smile:

**Comment by Hywan** [comment]
Can we close the issue then?

**Comment by evert** [comment]
No, it's still a bug

**Comment by patkar** [comment]
`\Sabre\Dav\Exception` should accept a HTTP code, not simply return 500 and the thrower should set the appropriate HTTP code when he throws the generic `\Sabre\Dav\Exception` instead one of the specific exception. This a serious and blocking bug..

**Comment by evert** [comment]
@patkar you should use $throwExceptions instead to get better exceptions with complete information.

I agree that using Sabre\DAV\Exception, but rather than looking at it as if everything gets turned into a 500, look at it as if the statuscode is simply meaningless in that context.

The 'base' exception in Sabre\DAV is Sabre\DAV\Exception. The exception classes that exist in the Sabre\DAV\Exception namespace (FileNotFound and others) are specifically intended for a _server_ to communicate an error to a _client_.

**Comment by patkar** [comment]
What do you mean with `$throwExceptions`?

I'm talking about as a consumer of the `\Sabre\DAV\Client` class, where we can't differ. See my comment in #613

**Comment by evert** [comment]
@patkar , Sabre\DAV\Client extends Sabre\HTTP\Client, which has a $throwExceptions property:

https://github.com/fruux/sabre-http/blob/master/lib/Client.php#L57
