### ISSUE TITLE
Receive always a 415 error.

### ISSUE THREAD

**Issue by marcelglaeser** [fruux/sabre-dav#663]
Hello sabre-dav community,

first: sry for my english!!! :)
my problems:
i try to run a sabre-dav server with symfony2 and i hope, that i'm not on the false place in this git!

All calendars are well synchronized in iCalendar, but if I make a schedule, I get a 414 error and this error message: 

```
21.05.15 16:44:02,353 CalendarAgent[253]: [com.apple.calendar.store.log.caldav.http.body] [<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.0.0-alpha1</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
  <s:message>This resource only supports valid iCalendar 2.0 data. Parse error: End of document reached prematurely</s:message>
</d:error>]
```

If i go with sabre/html to /dav/cal/principals/admin/calendar-proxy-read, I get this error message:

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.0.0-alpha1</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>
Could not find node at path: principals/admin/calendar-proxy-read
</s:message>
</d:error>
```

All other links running well! 
A long time ago, with version 1.*, i had no problems.

What can i do?? Thanks a lot!
Marcel

**Comment by evert** [comment]
Hi!

If you integrated your server with symfony, then my guess it that you are not correctly dealing with the request/response objects.

Both sabre/dav and symfony have their own http request and response objects, and in order to integrate the two, you need to make sure that sabre/dav has all the relevant data available.

My guess based on the error is that symfony did something with the request body, and sabre/dav is no longer able to access the body.

As for the second error, it's unrelated. To fix this you can simply create a new principal (probably in the `principals` table if you used the default PDO backends) and give the principal the uri: `principals/admin/calendar-proxy-read`.

**Comment by marcelglaeser** [comment]
Thanks,
that was my problem!! Now it works. :)
