### ISSUE TITLE
getUserName() method

### ISSUE THREAD

**Issue by benrubson** [fruux/sabre-dav#664]
Hello,

As a reminder / reference, here is an enhancement request related to issue #412.
Could you please implement getUserName() method described there ?

Thank you very much !

Ben

**Comment by evert** [comment]
Lets squeeze this in for 3.0.

**Comment by evert** [comment]
I'm very sorry to have to change my mind, but I have to.

I want the auth backends to remain as lightweight as possible. Right now there's just a `check` and a `challenge` method which makes it as concise as possible.

The auth backends are the only thing 'aware' of the method of authentication, and thus a potential user name. They communicate back what this username (or actually principal) is, but only when authentication is successful.

The auth plugin on the other hand is the 'thing' that throws the exception, and is not aware of any authentication details.

Note that all of this is new since 3.0. 

To get the 'username' information from the authentication backends to the plugin means that I have to add a rather-odd parameter to the `check` method, and I rather not. It complicates this too much for a feature that has a very small audience.

So I would recommend going back to the event-handler approach. You can really get all the info there too, the only difference is that you are responsible for parsing the `Authorization` string, which is pretty easy still with the `Sabre\Http`-related functions.

Sorry again.

**Comment by benrubson** [comment]
Evert, I understand, thank you very much for your answer.
Would you have a code example regarding the event-handler approach ?

In issue #412 you gave the following example :
```
$server->on('exception', function(Exception $e) {
  if ($e instanceof \Sabre\DAV\Exception\NotAuthenticated) {
     error_log($e->getMessage());
  }
});
```

Does ```$e->getMessage()``` contains the UserName ?
Every time authentication fails ?
Does the string use the same template every time ?

Thank you again !

Ben

**Comment by evert** [comment]
Hey Ben,

Ideally you don't rely on the actual messages. From that exception handler, you should access `$server->httpRequest->getHeader('Authorization')` and extract the information from that HTTP header.
