### ISSUE TITLE
Support pagination and sorting

### ISSUE THREAD

**Issue by kewisch** [fruux/sabre-dav#672]
We have a JSON plugin that allows retrieving events and contacts without the caldav queries. For scalability we'd like to paginate the results, at least for contacts. While I've managed to do this without modifying sabre-dav, I think it would be nice if it were possible to get members of a collection sorted and paginated.

I'm proposing to add a new interface `\Sabre\DAV\ISortableCollection` that a collection can optionally implement. It could look a bit like this:

```php
interface ISortableCollection extends ICollection {

    /**
     * Returns an array with all the child nodes, allowing for pagination and sorting
     *
     * @param int $offset Number of entries to skip
     * @param int $limit Maximum results, or 0 for unlimited
     * @param string $sort Sort field, or null for unsorted
     * @return DAV\INode[]
     */
    function getChildren($offset = 0, $limit = 0, $sort = null);

    /**
     * Retrieves the number of items in the collection
     *
     * @return int
     */
    function getChildCount();
}
```

On the next level, `\Sabre\CardDAV\AddressBook` and `\Sabre\CalDAV\Calendar` implement this interface, having their `getChildren` methods extended with the parameters and passing them on to the backend.

In the backend, the `getCards` and `getCalendarObjects` methods would be extended with the same parameters and finally do the database lookup.

What I am undecided on is how exactly the sort parameter would look like. For pagination it makes sense to sort the events in some way so the ordering is stable with different limit/offset parameters. What I have done now is to retrieve the FN from the contact and also save this in the database. I then passed the database field name as the `sort` parameter, which is obviously not ideal, and used this in the query.

On the other side, a flaw with this approach is that a contact may be missed when querying and another client adds or removes a contact in between. To solve this we would have to give each query an identifier and cache all calendar/contact paths on the first query until its done or encode this information in the next page link. In that case we could use `getMultipleChildren` and friends to retrieve the next batch of objects, but we would need a way to quickly get a list of all paths, or at least calendar ids. Bonus points for providing a builtin way to start such safe batched queries.

I'd love to hear your input on this, and I'm happy to spin up a patch if you are interested. If you would like to see what I've done, check out the [patch for our project](https://ci.open-paas.org/stash/users/pkewisch/repos/esn-sabre/commits/2b7c9e22e545aa11c4439b12b322498f1a5d1079).

**Comment by staabm** [comment]
`getChildren` is already defined on `ICollection` so this doesn't work as is.

Why do you need the `getChildCount()` method?

**Comment by kewisch** [comment]
I was able to overwrite the method signature of `getChildren` with the extended interface in the linked patch. Is that just not good style or will something actually break?

I need `getChildCount()` to check if I am on the last page, to see if it makes sense to show a next page link.

**Comment by staabm** [comment]
atm this only works, because all `ISortableCollection` args are optional and `ICollection` doesnt have any args.

see http://3v4l.org/9pabh and http://3v4l.org/elZH6 in which this type of construction triggers E_STRICT errors.

IMO from a design point of view it is also not correct that a `ISortableCollection` must also be a `ICollection`. For easier re-use and less coupling a `ISortableCollection` which doesn't extend anything also also doesn't collide with `ICollection` would be the way to go.

But lets see what the other guys think.

**Comment by evert** [comment]
Hi @kewisch ,

I'm with @staabm here a little bit. I don't really see a strong reason to overload `getChildren()` with new arguments. Adding a new method virtually has the same effect, but it will make it clearer what the intent is.

However, I have some other questions/issues.

**Returned value**

Almost all of the 'query' methods on nodes (such as the stuff for sync-collection, and calendarQuery, multiget, etc) don't return actual nodes, they just return the 'filenames' as a flat array.

This allows the 'querying mechanism' to be separated from 'fetching nodes and/or properties' and makes the internal code much simpler.

This is actually demonstrated in your actual patch as well, as the `getContacts()` method circumvents the ACL system by fetching everything 'manually'. 

**Sort field**

Not defining the sort field is indeed a little bit questionable... I'm not sure if we can leave it completely arbitrary, as then there's no real way for people to make any assumption on how they could sort it. In theory it would be possible to sort by WebDAV property, but then perhaps this problem should not be solved in individual nodes, just let the plugin figure it out.

Then again, that solves the problem for WebDAV collections, but you still can't really sort within vcards or iCalendar objects.

That said.. what is the actual use-case for you? Could you perhaps list in what ways you intend to sort? If we know of a more precise use-case, perhaps we can solve this differently.

Perhaps this is also worth mentioning on the TC-API call tomorrow?

**Paging**

I think I would prefer a server-controlled 'page number' system over a limit + offset. This solves a number of problems:

* The server can decide what page size makes sense from an optimization perspective
* Because the offsets are not arbitrary, it makes it a lot more feasible to cache.
* It also makes more sense for formats such as `HAL` where you typically only get a `next` link, _if_ there's more data.
* The 'Page number' doesn't have to be a number, it can be an arbitrary token, which solves your issue of changing the set in between fetching the pages.

**Comment by evert** [comment]
Closing this because there's not a clear actionable item. Re-open if needed =)
