### ISSUE TITLE
Simple, no-developer use case

### ISSUE THREAD

**Issue by naevtamarkus** [fruux/sabre-dav#679]
Dear Dav'ers,

First of all, thanks a lot for your efforts... The first time I made SabreDAV work on my personal web server marked the beginning of an era for me. I am not a web developer, but a user that wants to get a hold of my life (i.e. contacts and calendar) away from global providers. I have a web server at home, and I just want to store those contacts and events providing a simple interface for clients like Thunderbird and DavDroid. 

I installed SabreDav and (simply, with the groupwareserver.php) managed to do exactly that for the admin user, but it took some time to understand how to create a new user and change both passwords. Simple tasks, but absolutely necessary for a user like me that does not develop anything on top of SabreDAV. 

So, may I ask you for either (or both):
- Adding that functionality (adding users and changing passwords) to the groupware example server
- Creating a page in your webpage explaining how does the simple, no-developer use case works

```
# Initiate basic admin/admin access
mkdir data
chmod 777 data  ## please restrict it to the apache user!
cat examples/sql/sqlite.* | sqlite3 data/db.sqlite

# To calculate the password run 'php' without arguments and inside:
<? echo md5('myuser:SabreDAV:mypassword'); echo "\n"; ?>
# Then Ctrl+D

# Inside SQLite: 'sqlite3 data/db.sqlite':
# ADD user:
INSERT INTO users (username,digesta1) VALUES ('myuser',  '87fd274b_PREVIOUS_MD5_7c2f965da8ddf7');
INSERT INTO principals (uri,email,displayname) VALUES ('principals/myuser', 'user@example.org','User Name');
INSERT INTO principals (uri,email,displayname) VALUES ('principals/myuser/calendar-proxy-read', null, null);
INSERT INTO principals (uri,email,displayname) VALUES ('principals/myuser/calendar-proxy-write', null, null);
# DELETE user:                            
DELETE from users WHERE username='myuser';
# To change PASSWORD: 
UPDATE users SET digesta1='123fa_md5_412bc' WHERE username='myuser';
```
Then, groupwareserver.php comes with the functionality to create directories and add files, but they don't work out-of-the-box, and I could not find a document explaining how. It's not critical for me, but it's again an example of how this is not straightforward for a simple user.

Thanks a lot again!

**Comment by evert** [comment]
Hi Pablo,

We are doing a few things to resolve this:

1. Since sabre/dav 3.0 you can now actually create principals from the web interface. What we have not done yet, is also add the ability to create/manage passwords.
2. We also started a new project: sabre/katana. This project is specifically tailored for people such as yourself, the end-user. It comes with an installer and admin interface. This project is in early alpha, but go check it out if you want to give it a shot. sabre/dav in that project is stable, but the admin interface might still have bugs. We also can't guarantee that updates to new versions work pefectly.

Link: http://sabre.io/katana/

**Comment by naevtamarkus** [comment]
Thanks for the info... I am already trying it :)
