### ISSUE TITLE
Deleting events having attendees

### ISSUE THREAD

**Issue by GrahamLinagora** [fruux/sabre-dav#683]
I am working on a Sabre Caldav with MongoDB as backend and I encounter problem while deleting some events.
When creating an event having attendees, Sabre creates N events in the DB where N is the total number of event participants. And when the event is deleted by the organizer, only one of these event is removed form the DB. And the remaining events are still accessible to other attendees even though the event should have been deleted.

Should I implement the removal of all these events in the \Sabre\CalDAV\Backend\AbstractBackend sublclass or is this part of Sabre Caldav main code (and therefore my code does not trigger it properly) ?

**Comment by evert** [comment]
Hi Graham,

You should not. If all works correctly, the remaining events *should* all have gotten a `STATUS:CANCELLED` property. This allows the other clients to become aware of the fact that the previous event has been cancelled.

Does this make sense?

**Comment by GrahamLinagora** [comment]
Hi Evert and thanks for the quick answer !

It makes sense, and I'll make sure that my client handles well Canceled events.

However it seems to not work everytime. In my case it only works when the event only has 2 attendees (organizer + an other one). When there is more than 2 attendee the ```STATUS``` is not updated.
It works very well in a 2 persons event.

Any idea of what my implementation lacks ?

**Comment by evert** [comment]
No idea, this sounds like a bug though! It certainly *should* work...

**Comment by evert** [comment]
I am a bit sceptical if this is a bug within sabre/dav, just because you have your backend (mongoDb), so to further debug this, I think it would be good if you could share a bit more information.

Lets start with the first level. Hopefully we don't have to go super deep ;)

Could you share the events in your database, including the state that sort of demonstrates that the `STATUS` is not correctly set to `CANCELLED` ? Ideally you would share as many calendarobjects as you can that all have the same `UID`. There's likely an organizer copy, attendee copies and perhaps also the copies in the various inboxes would be helpful.

Let me know, or let me know if you have an alternative suggestion on how to dive deeper into this issue to find the root cause.

I'm also curious about your implementation of `getCalendarObjectByUID()`, and if you use shared calendars or not.

**Comment by GrahamLinagora** [comment]
I found what my mistake was, the ```STATUS``` of the events was ```CANCELLED``` but it was not properly shown in my mongo clients and also not properly handled by my code. So in fact there is no  bug.

Thanks a lot for your time and your fast answers

**Comment by evert** [comment]
Great to hear!
