### ISSUE TITLE
CalDAV delegation - how does it work with iOS

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#754]
Hi everybody,
I try to build a calenderserver with sabre-dav. I managed to install sabre-dav, create a calenderserver.php and a mysql database with two users and write access from one user to another.
(I used the explaination from: http://sabre.io/dav/caldav-proxy/)

In Thunderbird everything is working like a charm. I create two calenders in the network:
- https://192.168.5.32/sabre/calendarserver.php/calendars/admin/default/
- https://192.168.5.32/sabre/calendarserver.php/calendars/foo/default/

I use only the access data for user2 and can see and write into both calendars.
So here everything is fine.

Now it comes to iOS or MacOS. Here I can not create two calendars because MacOS prevents the creation of two similar calendars. The server address I use is: https://192.168.5.32/sabre/calendarserver.php/principals/admin/.

This shows me only the calendar from admin and I can not see the entries of foo. Does anybody has an advise if this is possible and which database entry is necessary?

As far as I understand sabre-dav right now there is a missing entry on screenshot 2. 
Screenshot 1 shows that admin has access to the calendar of foo.
But screenshot 2 should show that the calendar of foo should be in the calendar-proxy-write list of admin. Is that correct?

![calendarserver1](https://cloud.githubusercontent.com/assets/7803347/12199469/a7e1486e-b618-11e5-98b1-f99a9e9c6291.png)
![calendarserver2](https://cloud.githubusercontent.com/assets/7803347/12199468/a7d502ca-b618-11e5-9d99-57246e488465.png)

Best regards
Christoph

**Comment by evert** [comment]
Hi @christophdb ,

The way delegation works on Mac, is in two ways:

1. You will be able to see delegate calendars in the 'Window' menu in iCal.
2. In 'Preferences', 'Account' you see a 'Delegation' tab that should include the list of accounts you can access. If you check any of the boxes there, the delegate calendars should show up in your main list.

On iOS I am not aware that delegation is supported at all. You could attempt to setup a second sabre/dav account with a different principal url. I'm fairly sure that that did not work in previous versions of iOS, but it's possible that this has since then been fixed.

From the looks of your screenshot, it appears you've setup things correctly, but the best way to double-check this is to make sure it works in iCal.

I'm closing this ticket, but if you have any further questions, feel free to keep asking them in this ticket. I will see the notifications and I'm happy to discuss / debug further with you.

**Comment by m-a-v** [comment]
Remark: DAViCal supports delegation on iOS.

**Comment by larseggert** [comment]
Delegation on iOS would be great to have

**Comment by evert** [comment]
It's been years since I've looked at this or had a iOS device, but if I recall correctly calendar delegation always worked fine on iOS and delegated calendars magically appeared. However, iOS never allowed delegation to be set up and that had to be done in a different client or manually.

**Comment by larseggert** [comment]
I have delegation set up, and it works on iCal on MacOS. But not on iOS (same account).
