### ISSUE TITLE
Multiple Questions regarding sabredav: freebusy, delegation on iOS, IMip, hardware requirements

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#758]
Hi everybody,
I am playing with sabredav since four days now and I am completely amazed about this great software. As far as I can see know sabredav supports many features and it is often the clients that is not support something. Therefore I would like to ask for your experience regarding some features:

All questions are related to three clients: 
a) thunderbird mit lightning and sogo-connector, 
b) iCal on Mac 
c) iOS with default calendar-App.

1) freebusy
I activated the "schedule" Plugin in groupwareserver.php and immidiately I receive freebusy information on thunderbird if I create a new event.
But in iCal if I create an event and open up "availability" it shows me "availability is not supported". Well I get the german error messages: "Dieser Kalender unterstützt keine Verfügbarkeit". Is that correct? There is no freebusy support in iCal?

2) appointment confirmation
I create a new event in Thunderbird and invite another user. This user will receive on iCal an information about the event and can confirm and reject. Thunderbird does not receive any information about the decision. Neither there is a response email nor a accepted icon on the event itself. Well response email needs another plugin I know but I would have expected that thunderbird shows me a green check icon in front of the user. See screenshot:

![sabredav-event-invitation](https://cloud.githubusercontent.com/assets/7803347/12234154/12d9831c-b86b-11e5-8461-9286f41da4ab.png)

3) Delegation on iOS
Delegation of calendars in MacOS is working like a charm. On the iPhone delegation is not possible ("http://sabre.io/dav/clients/ios/)". I found some hints on the web that it should be possible using the uuid of the calender as the server address. Did you every tried this or is there any other possibility to use delegation on iOS?

4) IMip-Plugin
I do not understand the IMip-Plugin. Does it mean the the server sends the invitation emails and not the clients? Are the clients (thunderbird, iCal or iPhone) intelligent enough to detect that the server sends the invitations? 
As far as I understand your documentation I only have to add $server->addPlugin(new \Sabre\CalDAV\Schedule\IMipPlugin('info@example.org')); to the groupwareserver.php to enable emails with php mail function. is that correct? Or do I have to do more than to add this line and to replace info@example.org with my own emailadress?

5) Hardware requirements and max users?
do you have any recommendations regarding hardware in relation to the users? For example: for every 50 users you need x GB of RAM or something? Is it a problem that a high load or heavy usage of sabredav is slowing down other webpages on the server?

Thank you very much for your help.
Best regards
Christoph

**Comment by evert** [comment]
> I am playing with sabredav since four days now and I am completely amazed about this great software. As far as I can see know sabredav supports many features and it is often the clients that is not support something. Therefore I would like to ask for your experience regarding some features:

Thank you!

> All questions are related to three clients:
> a) thunderbird mit lightning and sogo-connector,
> b) iCal on Mac
> c) iOS with default calendar-App.

> 1) freebusy
> I activated the "schedule" Plugin in groupwareserver.php and immidiately I receive freebusy information on thunderbird if I create a new event.
> But in iCal if I create an event and open up "availability" it shows me "availability is not supported". Well I get the german error messages: "Dieser Kalender unterstützt keine Verfügbarkeit". Is that correct? There is no freebusy support in iCal?

Are you sure you are not confusing 'availability' and 'freebusy'? They are different things. Freebusy is supported since a long time, availability since version 3.1. Availability automatically works *if* you have the 'property storage' plugin enabled.

> 2) appointment confirmation
> I create a new event in Thunderbird and invite another user. This user will receive on iCal an information about the event and can confirm and reject. Thunderbird does not receive any information about the decision. Neither there is a response email nor a accepted icon on the event itself. Well response email needs another plugin I know but I would have expected that thunderbird shows me a green check icon in front of the user. See screenshot:

Is it possible that you just need to refresh thunderbird so it re-syncs with the server? If that doesn't solve it, perhaps you can install this add-on: https://addons.mozilla.org/en-US/thunderbird/addon/ics-inspector/?src=search and tell me for the specific event (by rightclicking) how the *exact* iCalendar object looks like after you accepted it on iCal.

> 3) Delegation on iOS
> Delegation of calendars in MacOS is working like a charm. On the iPhone delegation is not possible ("http://sabre.io/dav/clients/ios/)". I found some hints on the web that it should be possible using the uuid of the calender as the server address. Did you every tried this or is there any other possibility to use delegation on iOS?

If this works at all, you need the _principal url_ not an address to a calendar. This might work. Principal urls look like `/principals/[username]` by default.

> 4) IMip-Plugin
> I do not understand the IMip-Plugin. Does it mean the the server sends the invitation emails and not the clients? Are the clients (thunderbird, iCal or iPhone) intelligent enough to detect that the server sends the invitations?
> As far as I understand your documentation I only have to add $server->addPlugin(new \Sabre\CalDAV\Schedule\IMipPlugin('info@example.org')); to the groupwareserver.php to enable emails with php mail function. is that correct? Or do I have to do more than to add this line and to replace info@example.org with my own emailadress?

The server tells the client it sent the email on behalf of the client. I'm fairly certain this works for most caldav clients, but I'm not sure if it works for all. And yes, as long as PHP's `mail()` works on your machine this should.

> 5) Hardware requirements and max users?
do you have any recommendations regarding hardware in relation to the users? For example: for every 50 users you need x GB of RAM or something? Is it a problem that a high load or heavy usage of sabredav is slowing down other webpages on the server?

No recommendations. You'll have to try this out. If you run into performance problems, only then I can help.

**Comment by vladox** [comment]
Hi @christophdb 
I'm still trying to find out how the **appointment confirmation** works for not local accounts.
How are response emails handled by sabre/dav? Is a functionality that hasn't been implemented yet?
Thanks for any hint.
Vlad
