### ISSUE TITLE
private Events

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#760]
Hi everybody,
I am using SabreDAV as CalDAV Server and I have a question regarding "private events". I can create events on thunderbird and mark them as "private". The ICS File has now the entry: CLASS:PRIVATE.

Now I grant read-access to another user and he has a look at my calendar. He has an iPhone or is using iCal and he can see the complete entry. It seems that Apple is ignoring the flag "private". Is that correct? 

I ask because I found a hint that apple is support the "private flag". See here: https://support.apple.com/kb/PH20322?locale=en_US&viewlocale=en_US

Now my two questions:
1) does apple devices support "private events"?
2) if no, is there a way to rewrite the content of all events for other users with read/write access to something generic like "this is a private event"?

Thanks and best regards
Christoph

**Comment by evert** [comment]
Hi Cristoph,

I would say that there's really no such thing as a real private event in this context. Neither apple nor sabredav is really doing anything wrong I think. The `CLASS` property has no functionality or restrictions associated to it in either scheduling, CalDAV, iCalendar, iTip or CalDAV proxy.

Therefore the class just means to be used as an indicator to the user. If you set `CLASS` to `PRIVATE` or `CONFIDENTIAL` then another user can see this and treat that event privately. It's a property for humans, not machines.

The link you sent is interesting though, because it indicates that while I think this is true, apple decided to give special meaning to the `CLASS` property in iCloud. But note that this is an iCloud feature, not iPhone or iCal. sabre/dav simply does not do this, and we don't currently have a feature that would allow this.

**Comment by evert** [comment]
Closing this as there was no further feedback.
