### ISSUE TITLE
Problem with connecting to CalDAV via HTTPS

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [fruux/sabre-dav#826]
It doesn't show calendars from CalDAV using HTTPS connection, it works fine with HTTP.
I connect using https://sabredav.yetiforce.com/3.1.3/dav.php/principals/admin/ 
I can't see any connection in Apache logs.
It works fine on other systems, eg. Android and Windows.
Contact synchronization works with HTTPS.

SabreDav: 3.1.3
Operating system: OS X Mavericks 10.9

Address: https://sabredav.yetiforce.com/3.1.3/dav.php
Login: admin
Password: admin
Logs: https://sabredav.yetiforce.com/3.1.3/logs/

**Comment by evert** [comment]
Does your server require SSI? It's possible that mavericks can't connect to it. Do you remember if Mavericks had issues with that @DominikTo ?

**Comment by DominikTo** [comment]
I guess @evert meant [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). That could indeed be an issue if Mavericks doesn't support SNI (couldn't figure out since when OS X supports it), but it doesn't look like this server uses SNI.

If @mariuszkrzaczkowski doesn't even see anything in the connection logs, my guess is that it is an issue directly in iCal - maybe because the port in its account profile is not properly updated when `http` is switched to `https`. It might be worth a try to delete the account in iCal and then try to recreate it. You could also try adding `:443` to the URL.

**Comment by mariuszkrzaczkowski** [comment]
It started working when I added the port. Thanks a lot
https://sabredav.yetiforce.com:443/3.1.3/dav.php

**Comment by evert** [comment]
Weird! Glad you figured it out though
