### ISSUE TITLE
3.2:  getCalendarsForUser() does not return share_displayname

### ISSUE THREAD

**Issue by git-marijus** [fruux/sabre-dav#847]
Is that by design or is it missing?

**Comment by evert** [comment]
Probably missing!

**Comment by evert** [comment]
I was mistaken, this was not actually used there. The share_displayname is actually only used when getting a list of people who are invited to a share.

So the sharee_displayname _is_ used, but it's only used in `getInvites()` and not `getCalendarsForUser()`

**Comment by git-marijus** [comment]
> So the sharee_displayname is used, but it's only used in getInvites() and not getCalendarsForUser()

This is a pitty...
If i have 10 users with a default calendar called "My Calendar" and those calendars will be shared between eachother `getCalendarsForUser()` will return 10 calendars with the same name for each user (one can't say which calendar is whos).
The `Sharee()` class gives the possibility to set sharee_displayname with `updateInvites()` which makes it simple to name the shared calendar "My Calendar (John Doe)" in sharee_displayname.

If `getCalendarsForUser()` would also return sharee_displayname (it querys the table anyway) it would be very simple to show the the 9 shared MyCalendars with the username attached and the not shared calendars with their "real name". 

Since this is not the case atm. we have to query the same table once more with `getInvites()` to get the info...

Might make it a feature request...

**Comment by evert** [comment]
There's a confusion here because "sharee_displayname" is the "displayname" of the user who is sharing, it is not the displayname for a calendar. Displayname is a more generic term for naming stuff in webdav, but yea.. it doesn't reference the calendar in this case.

We have a copy of the displayname of the user who shared something, because we keep it separate from the real displayname of the underlying principal. This is to support inviting people who are not users which is something we might add in the future.

**Comment by git-marijus** [comment]
Ok... Thanks for the explanation!
I think the naming of the tables confused me...
