### ISSUE TITLE
[CardDav] Contacts coding problem

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [fruux/sabre-dav#858]
I have a weird problem with coding contacts, when I synchronize contacts in thunderbird  with sogoconnector then sometimes the coding is wrong.
When I add a contact in an android phone then it's not coded properly in thunderbird.
When I add a contact in an iOS phone then the coding is okay. 
When I add a contact in thunderbird then in both, android and iOS, the coding is okay.

When I download vacrd from SabreDAV Browser they are always the same, what can be the problem?

**Comment by evert** [comment]
I'll need a lot more than that to help! Coding is wrong can mean a lot of different things.

**Comment by mariuszkrzaczkowski** [comment]
I recorded a video showing what the problem is.
![animation](https://cloud.githubusercontent.com/assets/10198654/16444539/c097b962-3dde-11e6-88f5-92ff3c2899b5.gif)

**Comment by evert** [comment]
Hi @mariuszkrzaczkowski ,

Thanks for the video. If I interpret it correctly, the vCard is broken after DavDroid touches it. Is that correct, or did I make the wrong conclusion?

If so, I would love to take a look at the vcard *after* it breaks. Could you upload a copy somewhere? It's important that you don't just use a github comment to copy-paste them because I need the actual bytes inside of it to be correct.

I am thinking that if it was indeed davdroid doing this, that it's also the most likely that this is a bug that should be submit to the davdroid project, but I'm curious how the vcard looks like regardless.

**Comment by mariuszkrzaczkowski** [comment]
I don't know whether or not it's a problem with DavDroid, because when I created it using script in PHP using sabre/vobject I get the same problem.
I attach a few examples of vCard files downloaded from SabreDAV browser.

[vcards.zip](https://github.com/fruux/sabre-dav/files/341318/vcards.zip)

**Comment by evert** [comment]
How are you creating it using a script in PHP? sabre/vobject doesn't specifically restrict you from creating broken files with invalid characters, so it's possible that your PHP source file is simply not set to UTF-8.

I also took a look at the zip file, and literally every vcard in here _is_ actually correct UTF-8. There's no broken data in there.

**Comment by mariuszkrzaczkowski** [comment]
Yes I know vcard files are properly coded, I checked it in the database, they are okay as well. What can be the problem?

**Comment by mariuszkrzaczkowski** [comment]
I'm attaching the synchronization logs
[davDebug.txt](https://github.com/fruux/sabre-dav/files/345979/davDebug.txt)

**Comment by evert** [comment]
If it's all correctly encoded, but it shows up incorrectly in a client, then the bug must be in that client.
