### ISSUE TITLE
vCard UID -- belongs to a card representation?

### ISSUE THREAD

**Issue by neandr** [fruux/sabre-dav#906]
https://tools.ietf.org/html/rfc6350#section-6.7.6 says for the  'UID':
> Purpose:  To specify a value that represents a globally unique identifier corresponding to the entity associated with the vCard.

Shouldn't that imply an vCard imported from another source already having a UID would hold the same UID in the system which imports that card. So always and on all card systems a specific card would have the same (unchanged) UID. 

AFAIS fruux changes the UID for a card with importing. Checked with exporting from fruux and compared with the one which was imported.

**Comment by evert** [comment]
Hi @neandr ,

This doesn't sound right. We set UID's, but only for the cards that don't already have one. I agree that vCard UID's _should_ be stable.

**Comment by evert** [comment]
Scrap that, it turns out we do reset them. I don't know why we originally did that. A normal (non-import) does do this correctly. I feel that we may have added this because people were doing the same import multiple times and this avoids problems with that.

The regular PUT requests does maintain the UID (if it's set). Since this is a fruux bug, it doesn't really belong here though. Not sure what we should do about it. This repository is more about sabre/dav and general caldav/carddav issues. Maybe @DominikTo has an opinion?

**Comment by DominikTo** [comment]
The hunch @evert had is correct, fruux sets new UIDs on purpose to deal with problems when people are doing the same import multiple times.
