### ISSUE TITLE
getPrincipalByPath() is called even if user was not successfully authenticated (yet)

### ISSUE THREAD

**Issue by mbiebl** [fruux/sabre-dav#913]
Since the upgrade from 3.1 to 3.2, I see a strange behaviour.
It seems that sabre-dav calls getPrincipalByPath (Sabre\DAVACL\PrincipalBackend) even before the user has been authenticated. After adding some debug output to
the PrincipalBackend getPrincipalByPath() method and AuthBackend check() method, I get with 
3.1
```
Nov 25 18:29:24 pluto apache2[30340]: check: no authorization information
Nov 25 18:29:24 pluto apache2[30722]: check: testuser
Nov 25 18:29:24 pluto apache2[30722]: getPrincipalByPath principals/testuser
```
with 3.2 this looks like
```
Nov 25 18:17:23 pluto apache2[30384]: check: no authorization information
Nov 25 18:17:23 pluto apache2[30384]: getPrincipalByPath principals/testuser <----
Nov 25 18:17:23 pluto apache2[30386]: check: testuser
Nov 25 18:17:23 pluto apache2[30386]: getPrincipalByPath principals/testuser
```
A git bisect points to #657.

**Comment by mbiebl** [comment]
My custom backend assumes that the user has been successfully authenticated before getPrincipalByPath() is called, so it is broken by the new behaviour. 
I'm not sure if the new behaviour works as designed and I need to update my code (in which case I would be grateful for some pointers) or if this behaviour is buggy.

**Comment by mbiebl** [comment]
The relevant commit is 28bbce1c30abada11d0e1d49094c120ff1e3084c

**Comment by mbiebl** [comment]
So, using
```
$aclPlugin->allowUnauthenticatedAccess = false;
```
brought the old behaviour back and I'm happy again. I wonder if the default behaviour should be changed to false though, or at least have this documented more prominently.

Feel free to keep the bug report open if you agree with the latter, otherwise it can be closed.

**Comment by evert** [comment]
Hi @mbiebl ,

The getPrincipalByPath function is not really considered an 'auhtenticated function'. The server will call this function whenever it needs more information about a principal.

There's a bunch of situations where getPrincipalByPath is needed, but if a client would for example do a straight-up `PROPFIND` on a principal's path, the steps taken are (on a high-level) as follows:

1. Is there a valid auth header? If so: log the user in. Either way continue.
2. Grab the information using getPrincipalByPath
3. If the information public, send back response. Otherwise, continue to 4
4. Was the user logged in in step 1? Require auth. If not, go to step 5
5. Send 403

This is a pretty advanced new feature in 3.2 and basically allows for parts of your WebDAV tree to be accessible by people that don't require authentication. This is useful for for example public calendars.

There's some more information about this news system in the documentation:

http://sabre.io/dav/upgrade/3.1-to-3.2/

And to answer your question:

1. Changing the `allowUnauthenticatedAccess` flag indeed goes back to the old behavior and this is the easy fix.
2. I would still try to fix your backends to not rely on a user to be logged in if you can. If you don't, there's no major harm but you might miss out on some future features such as calendar publishing.
